bukutamu-laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BukutamuController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('bukutamu', BukutamuController::class);

bukutamu-laravel/app/Models/Bukutamu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bukutamu extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $table = 'bukutamu';

    protected $fillable = [
        'nama',
        'email',
        'website',
        'komentar'
    ];
}

bukutamu-laravel/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

bukutamu-laravel/app/Http/Controllers/BukutamuController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use App\Models\Bukutamu;
use Illuminate\Http\Request;

class BukutamuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bukutamu = DB::table('bukutamu')->paginate(15);

        return view('bukutamu.index', compact('bukutamu'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bukutamu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'email' => 'required',
            'komentar' => 'required'
        ]);

        Bukutamu::create($request->all());

        return redirect()->route('bukutamu.index')
            ->with('success', 'Sukses menyimpan data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bukutamu  $bukutamu
     * @return \Illuminate\Http\Response
     */
    public function show(Bukutamu $bukutamu)
    {
        return view('bukutamu.show', compact('bukutamu'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bukutamu  $bukutamu
     * @return \Illuminate\Http\Response
     */
    public function edit(Bukutamu $bukutamu)
    {
        return view('bukutamu.edit', compact('bukutamu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bukutamu  $bukutamu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bukutamu $bukutamu)
    {
        $request->validate([
            'nama' => 'required',
            'email' => 'required',
            'komentar' => 'required'
        ]);
        $bukutamu->update($request->all());

        return redirect()->route('bukutamu.index')
            ->with('success', 'Sukses update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bukutamu  $bukutamu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bukutamu $bukutamu)
    {
        $bukutamu->delete();

        return redirect()->route('bukutamu.index')
            ->with('success', 'Sukses hapus data');
    }
}

bukutamu-laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

bukutamu-laravel/resources/views/bukutamu/create.blade.php
@extends('layout')
 
@section('content')
<div class="row mt-5 mb-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Input Data</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-secondary" href="{{ route('bukutamu.index') }}"> Back</a>
        </div>
    </div>
</div>
 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Error!</strong> Ada kesalahan<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('bukutamu.store') }}" method="POST">
    @csrf
 
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                <input type="text" name="nama" class="form-control" placeholder="Nama">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Website:</strong>
                <input type="text" name="website" class="form-control" placeholder="Website">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Komentar:</strong>
                <textarea class="form-control" style="height:150px" name="komentar" placeholder="Komentar"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 
</form>
@endsection

bukutamu-laravel/resources/views/bukutamu/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row mt-5 mb-5">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Aplikasi Bukutamu</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('bukutamu.create') }}"> Input Data</a>
            </div>
        </div>
    </div>
 
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
 
    <table class="table table-bordered">
        <tr>
            <th width="20px" class="text-center">No</th>
            <th>Nama</th>
            <th>Email</th>
            <th>Website</th>
            <th width="280px"class="text-center">Komentar</th>
        </tr>
        @foreach ($bukutamu as $bt)
        <tr>
            <td class="text-center">{{ ++$i }}</td>
            <td>{{ $bt->nama }}</td>
            <td>{{ $bt->email }}</td>
            <td>{{ $bt->website }}</td>
            <td>{{ $bt->komentar }}</td>
        </tr>
        @endforeach
    </table>
 
    {!! $bukutamu->links() !!}
 
@endsection

bukutamu-laravel/resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Belajar Laravel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
 
<div class="container">
    @yield('content')
</div>
 
</body>
</html>